[package]
name = "as2mca-api"
version = "0.1.0"
edition = "2024"
authors = ["Falldot <fe.offep@gmail.com>"]
readme = "README.md"
description = "Aplication Server 2MCA API HTTP Client"
license = "MIT"
homepage = "https://github.com/plp-lang/as2mca-api-rs"
repository = "https://github.com/plp-lang/as2mca-api-rs"
categories = [
  "web-programming::http-client"
]
keywords = [
  "async",
  "api",
  "client",
  "2mca",
  "cbs"
]

[lints.clippy]
complexity = { level = "deny", priority = -1 }
suspicious =  { level = "deny", priority = -1 }
correctness =  { level = "deny", priority = -1 }

perf =  { level = "warn", priority = -1 }
cargo =  { level = "warn", priority = -1 }
style =  { level = "warn", priority = -1 }
nursery =  { level = "warn", priority = -1 }
pedantic =  { level = "warn", priority = -1 }

multiple_crate_versions = "allow"

[dependencies]
tracing = { version = "0.1.44", features = ["attributes"] }
quick-xml = { version = "0.41.0", features = ["serialize"] }
reqwest = { version = "0.13.4", features = ["cookies"] }
serde = { version = "1.0.229", features = ["derive"] }
thiserror = "2.0.19"

[dev-dependencies]
rstest = "0.26.1"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tokio = { version = "1.53.1", features = ["full"] }
local-ip-address = "0.6.13"
mac_address = "1.1.8"
whoami = "2.1.2"
regex = "1.13.1"

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
